# Generated by Django 3.1.7 on 2021-03-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('courier_type', models.CharField(max_length=4)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('earnings', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourierRegion',
            fields=[
                ('region', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourierWorkingHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couriers.courier')),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='regions',
            field=models.ManyToManyField(to='couriers.CourierRegion'),
        ),
    ]
