# Generated by Django 3.1.7 on 2021-03-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.FloatField(max_length=5)),
                ('region', models.IntegerField()),
                ('assign_time', models.TimeField(blank=True, null=True)),
                ('complete_time', models.TimeField(blank=True, null=True)),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couriers.courier')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
