# Generated by Django 3.1.7 on 2021-03-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210326_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhour',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='deliveryhour',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='assign_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
