# Generated by Django 3.1.7 on 2021-03-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
        ('orders', '0004_auto_20210326_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assigned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='couriers.courier'),
        ),
    ]
